image: Visual Studio 2022
configuration:
  - Release
platform:
  - x86
  - x64
cache:
  - C:\tools\vcpkg\installed\ -> InstallVcpkgDeps.bat
install:
  - vcpkg integrate install
  - call InstallVcpkgDeps.bat
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true
build:
  project: NAS2D.sln
artifacts:
  - path: "Temporary/*.zip"
    name: BuildArtifacts
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - '%APPVEYOR_BUILD_FOLDER%\test\%PLATFORM%\%CONFIGURATION%\test.exe'
deploy:
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    CONFIGURATION: Release
  artifact: BuildArtifacts
  description: ''
  provider: GitHub
  auth_token:
    secure: sNvqUedX6OZ4kgbx8OYUbqq3mSIg1Y8QCW+7w/piSSieaPZnK911w1JKpmQIXjPU
